/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DAORouter, DAORouterInterface } from "../DAORouter";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220b34c420cc250f3d58b75f266d2ecef36707ee881af8979c4a68208ab488a196d64736f6c63430008070033";

export class DAORouter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DAORouter> {
    return super.deploy(overrides || {}) as Promise<DAORouter>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DAORouter {
    return super.attach(address) as DAORouter;
  }
  connect(signer: Signer): DAORouter__factory {
    return super.connect(signer) as DAORouter__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DAORouterInterface {
    return new utils.Interface(_abi) as DAORouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DAORouter {
    return new Contract(address, _abi, signerOrProvider) as DAORouter;
  }
}
